### ISSUE TITLE
left in a console log

### ISSUE THREAD

**Issue by jwld** [FACN1/week5-D-REEM-TEAM#27]
https://github.com/FACN1/week5-D-REEM-TEAM/blob/master/src/filterResponse.js#L7

**Comment by SavageWilliam** [comment]
^^ haha cracking the wip @JWLD.

Good use of github!


Also declare url twice. Keeping it inside the function is good, if its not required elsewhere.
https://github.com/FACN1/week5-D-REEM-TEAM/blob/master/src/routes/search.js#L6

**Comment by jwld** [comment]
:fire:

**Comment by edgarfinn** [comment]
Thanks both. Both should have been resolved now :fire_engine: :bowtie: 👍 :1st_place_medal:
