### ISSUE TITLE
using router.router not great readability

### ISSUE THREAD

**Issue by mattlub** [FACN1/week5-D-REEM-TEAM#35]
should probably just use 'router' instead of router.router?

https://github.com/FACN1/week5-D-REEM-TEAM/blob/master/src/server.js#L11

Either change router exports or definition of router at the top of the file

**Comment by SavageWilliam** [comment]
Good comment.

similarly
```js
 module.exports = {
  start: startServer
}
```

This exporting object pattern works well on the frnt end, with self invoking functions. 

But with your node modules, it would be much better to declare the startServer function

```js
server.startServer = function() {
...
}
```

and then just call

```js
module.exports = startServer
```

Its perfectly fine to export a function. In front end javascript, the use of objects is just a way to cleanly return what you want. 

Then from the module which 'startServer' is required in... 
```
var server = require('.server')

server.start()
```

**Comment by macintoshhelper** [comment]
Fixed in https://github.com/FACN1/week5-D-REEM-TEAM/pull/55
