### ISSUE TITLE
server.js module.exports potentially slightly confusing

### ISSUE THREAD

**Issue by mattlub** [FACN1/week5-D-REEM-TEAM#38]
I found it slightly confusing to export the function with a different name, albeit quite similar.
Could do

server = module.exports = {};

server.start = function ...

https://github.com/FACN1/week5-D-REEM-TEAM/blob/master/src/server.js#L22

**Comment by macintoshhelper** [comment]
Fixed in https://github.com/FACN1/week5-D-REEM-TEAM/pull/50 - please confirm if fixed by closing

**Comment by mattlub** [comment]
nice 👍
