### ISSUE TITLE
Why does your server support mp4 mime type

### ISSUE THREAD

**Issue by des-des** [FACN1/week5-D-REEM-TEAM#46]
This seems strange.

**Comment by macintoshhelper** [comment]
I copy/pasted the mimeTypes object from MDN vanilla static file code snippet for future expandability. mp4 is unlikely to be hosted for this project though, so I'll remove :)

**Comment by macintoshhelper** [comment]
Fixed in https://github.com/FACN1/week5-D-REEM-TEAM/pull/52
